package com.peknight.demo.frontend.apache.echarts.chart.lines

import com.peknight.demo.frontend.apache.echarts.`export`.SeriesInjectedOption
import com.peknight.demo.frontend.apache.echarts.chart.helper.LineDrawEffectOption
import com.peknight.demo.frontend.apache.echarts.component.marker.{MarkAreaOption, MarkLineOption, MarkPointOption}
import com.peknight.demo.frontend.apache.echarts.util.*
import com.peknight.demo.frontend.apache.echarts.{Number, clean}
import com.peknight.demo.frontend.ecomfe.zrender.animation.AnimationEasing

import scala.scalajs.js

trait LinesSeriesOption extends LinesSeriesOptionInner with SeriesInjectedOption

object LinesSeriesOption:
  def apply(id: js.UndefOr[OptionId] = js.undefined,
            name: js.UndefOr[OptionName] = js.undefined,
            z: js.UndefOr[Number] = js.undefined,
            zlevel: js.UndefOr[Number] = js.undefined,
            animation: js.UndefOr[Boolean] = js.undefined,
            animationThreshold: js.UndefOr[Number] = js.undefined,
            animationDuration: js.UndefOr[Number | AnimationDurationCallback] = js.undefined,
            animationEasing: js.UndefOr[AnimationEasing] = js.undefined,
            animationDelay: js.UndefOr[Number | AnimationDelayCallback] = js.undefined,
            animationDurationUpdate: js.UndefOr[Number | AnimationDurationCallback] = js.undefined,
            animationEasingUpdate: js.UndefOr[AnimationEasing] = js.undefined,
            animationDelayUpdate: js.UndefOr[Number | AnimationDelayCallback] = js.undefined,
            color: js.UndefOr[ZRColor | js.Array[ZRColor]] = js.undefined,
            colorLayer: js.UndefOr[js.Array[js.Array[ZRColor]]] = js.undefined,
            emphasis: js.UndefOr[LinesStateOption[CallbackDataParams] & DefaultStatesMixinEmphasis & StatesEmphasisOptionMixin] = js.undefined,
            select: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any & StatesSelectOptionMixin] = js.undefined,
            blur: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any] = js.undefined,
            silent: js.UndefOr[Boolean] = js.undefined,
            blendMode: js.UndefOr[String] = js.undefined,
            cursor: js.UndefOr[String] = js.undefined,
            dataGroupId: js.UndefOr[OptionId] = js.undefined,
            data: js.UndefOr[js.Array[LinesDataItemOption] | js.Array[Number]] = js.undefined,
            colorBy: js.UndefOr[ColorBy] = js.undefined,
            legendHoverLink: js.UndefOr[Boolean] = js.undefined,
            progressive: js.UndefOr[Number | false] = js.undefined,
            progressiveThreshold: js.UndefOr[Number] = js.undefined,
            progressiveChunkMode: js.UndefOr["mod"] = js.undefined,
            coordinateSystem: js.UndefOr[String] = js.undefined,
            hoverLayerThreshold: js.UndefOr[Number] = js.undefined,
            seriesLayoutBy: js.UndefOr[SeriesLayoutBy] = js.undefined,
            labelLine: js.UndefOr[LabelLineOption] = js.undefined,
            labelLayout: js.UndefOr[LabelLayoutOption | LabelLayoutOptionCallback] = js.undefined,
            stateAnimation: js.UndefOr[AnimationOption] = js.undefined,
            universalTransition: js.UndefOr[Boolean | UniversalTransitionOption] = js.undefined,
            selectedMap: js.UndefOr[js.Dictionary[Boolean] | "all"] = js.undefined,
            selectedMode: js.UndefOr["single" | "multiple" | "series" | Boolean] = js.undefined,
            lineStyle: js.UndefOr[LinesLineStyleOption[js.Function1[CallbackDataParams, ZRColor] | ZRColor]] = js.undefined,
            label: js.UndefOr[SeriesLineLabelOption] = js.undefined,
            xAxisIndex: js.UndefOr[Number] = js.undefined,
            yAxisIndex: js.UndefOr[Number] = js.undefined,
            xAxisId: js.UndefOr[String] = js.undefined,
            yAxisId: js.UndefOr[String] = js.undefined,
            geoIndex: js.UndefOr[Number] = js.undefined,
            geoId: js.UndefOr[String] = js.undefined,
            polarIndex: js.UndefOr[Number] = js.undefined,
            polarId: js.UndefOr[String] = js.undefined,
            calendarIndex: js.UndefOr[Number] = js.undefined,
            calendarId: js.UndefOr[String] = js.undefined,
            large: js.UndefOr[Boolean] = js.undefined,
            largeThreshold: js.UndefOr[Number] = js.undefined,
            symbol: js.UndefOr[js.Array[String] | String] = js.undefined,
            symbolSize: js.UndefOr[js.Array[Number] | Number] = js.undefined,
            effect: js.UndefOr[LineDrawEffectOption] = js.undefined,
            polyline: js.UndefOr[Boolean] = js.undefined,
            clip: js.UndefOr[Boolean] = js.undefined,
            dimensions: js.UndefOr[DimensionDefinitionLoose | js.Array[DimensionDefinitionLoose]] = js.undefined,
            markArea: js.UndefOr[MarkAreaOption] = js.undefined,
            markLine: js.UndefOr[MarkLineOption] = js.undefined,
            markPoint: js.UndefOr[MarkPointOption] = js.undefined,
            tooltip: js.UndefOr[SeriesTooltipOption] = js.undefined): LinesSeriesOption =
    val _id: js.UndefOr[OptionId] = id
    val _name: js.UndefOr[OptionName] = name
    val _z: js.UndefOr[Number] = z
    val _zlevel: js.UndefOr[Number] = zlevel
    val _animation: js.UndefOr[Boolean] = animation
    val _animationThreshold: js.UndefOr[Number] = animationThreshold
    val _animationDuration: js.UndefOr[Number | AnimationDurationCallback] = animationDuration
    val _animationEasing: js.UndefOr[AnimationEasing] = animationEasing
    val _animationDelay: js.UndefOr[Number | AnimationDelayCallback] = animationDelay
    val _animationDurationUpdate: js.UndefOr[Number | AnimationDurationCallback] = animationDurationUpdate
    val _animationEasingUpdate: js.UndefOr[AnimationEasing] = animationEasingUpdate
    val _animationDelayUpdate: js.UndefOr[Number | AnimationDelayCallback] = animationDelayUpdate
    val _color: js.UndefOr[ZRColor | js.Array[ZRColor]] = color
    val _colorLayer: js.UndefOr[js.Array[js.Array[ZRColor]]] = colorLayer
    val _emphasis: js.UndefOr[LinesStateOption[CallbackDataParams] & DefaultStatesMixinEmphasis & StatesEmphasisOptionMixin] = emphasis
    val _select: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any & StatesSelectOptionMixin] = select
    val _blur: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any] = blur
    val _silent: js.UndefOr[Boolean] = silent
    val _blendMode: js.UndefOr[String] = blendMode
    val _cursor: js.UndefOr[String] = cursor
    val _dataGroupId: js.UndefOr[OptionId] = dataGroupId
    val _data: js.UndefOr[js.Array[LinesDataItemOption] | js.Array[Number]] = data
    val _colorBy: js.UndefOr[ColorBy] = colorBy
    val _legendHoverLink: js.UndefOr[Boolean] = legendHoverLink
    val _progressive: js.UndefOr[Number | false] = progressive
    val _progressiveThreshold: js.UndefOr[Number] = progressiveThreshold
    val _progressiveChunkMode: js.UndefOr["mod"] = progressiveChunkMode
    val _coordinateSystem: js.UndefOr[String] = coordinateSystem
    val _hoverLayerThreshold: js.UndefOr[Number] = hoverLayerThreshold
    val _seriesLayoutBy: js.UndefOr[SeriesLayoutBy] = seriesLayoutBy
    val _labelLine: js.UndefOr[LabelLineOption] = labelLine
    val _labelLayout: js.UndefOr[LabelLayoutOption | LabelLayoutOptionCallback] = labelLayout
    val _stateAnimation: js.UndefOr[AnimationOption] = stateAnimation
    val _universalTransition: js.UndefOr[Boolean | UniversalTransitionOption] = universalTransition
    val _selectedMap: js.UndefOr[js.Dictionary[Boolean] | "all"] = selectedMap
    val _selectedMode: js.UndefOr["single" | "multiple" | "series" | Boolean] = selectedMode
    val _lineStyle: js.UndefOr[LinesLineStyleOption[js.Function1[CallbackDataParams, ZRColor] | ZRColor]] = lineStyle
    val _label: js.UndefOr[SeriesLineLabelOption] = label
    val _xAxisIndex: js.UndefOr[Number] = xAxisIndex
    val _yAxisIndex: js.UndefOr[Number] = yAxisIndex
    val _xAxisId: js.UndefOr[String] = xAxisId
    val _yAxisId: js.UndefOr[String] = yAxisId
    val _geoIndex: js.UndefOr[Number] = geoIndex
    val _geoId: js.UndefOr[String] = geoId
    val _polarIndex: js.UndefOr[Number] = polarIndex
    val _polarId: js.UndefOr[String] = polarId
    val _calendarIndex: js.UndefOr[Number] = calendarIndex
    val _calendarId: js.UndefOr[String] = calendarId
    val _large: js.UndefOr[Boolean] = large
    val _largeThreshold: js.UndefOr[Number] = largeThreshold
    val _symbol: js.UndefOr[js.Array[String] | String] = symbol
    val _symbolSize: js.UndefOr[js.Array[Number] | Number] = symbolSize
    val _effect: js.UndefOr[LineDrawEffectOption] = effect
    val _polyline: js.UndefOr[Boolean] = polyline
    val _clip: js.UndefOr[Boolean] = clip
    val _dimensions: js.UndefOr[DimensionDefinitionLoose | js.Array[DimensionDefinitionLoose]] = dimensions
    val _markArea: js.UndefOr[MarkAreaOption] = markArea
    val _markLine: js.UndefOr[MarkLineOption] = markLine
    val _markPoint: js.UndefOr[MarkPointOption] = markPoint
    val _tooltip: js.UndefOr[SeriesTooltipOption] = tooltip
    val linesSeriesOption: LinesSeriesOption = new LinesSeriesOption:
      override val mainType: js.UndefOr[MainType] = "series"
      override val `type`: js.UndefOr[Type] = "lines"
      override val id: js.UndefOr[OptionId] = _id
      override val name: js.UndefOr[NameType] = _name
      override val z: js.UndefOr[Number] = _z
      override val zlevel: js.UndefOr[Number] = _zlevel
      override val animation: js.UndefOr[Boolean] = _animation
      override val animationThreshold: js.UndefOr[Number] = _animationThreshold
      override val animationDuration: js.UndefOr[Number | AnimationDurationCallback] = _animationDuration
      override val animationEasing: js.UndefOr[AnimationEasing] = _animationEasing
      override val animationDelay: js.UndefOr[Number | AnimationDelayCallback] = _animationDelay
      override val animationDurationUpdate: js.UndefOr[Number | AnimationDurationCallback] = _animationDurationUpdate
      override val animationEasingUpdate: js.UndefOr[AnimationEasing] = _animationEasingUpdate
      override val animationDelayUpdate: js.UndefOr[Number | AnimationDelayCallback] = _animationDelayUpdate
      override val color: js.UndefOr[ZRColor | js.Array[ZRColor]] = _color
      override val colorLayer: js.UndefOr[js.Array[js.Array[ZRColor]]] = _colorLayer
      override val emphasis: js.UndefOr[LinesStateOption[CallbackDataParams] & DefaultStatesMixinEmphasis & StatesEmphasisOptionMixin] = _emphasis
      override val select: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any & StatesSelectOptionMixin] = _select
      override val blur: js.UndefOr[LinesStateOption[CallbackDataParams] & js.Any] = _blur
      override val silent: js.UndefOr[Boolean] = _silent
      override val blendMode: js.UndefOr[String] = _blendMode
      override val cursor: js.UndefOr[String] = _cursor
      override val dataGroupId: js.UndefOr[OptionId] = _dataGroupId
      override val data: js.UndefOr[DataType] = _data
      override val colorBy: js.UndefOr[ColorBy] = _colorBy
      override val legendHoverLink: js.UndefOr[Boolean] = _legendHoverLink
      override val progressive: js.UndefOr[Number | false] = _progressive
      override val progressiveThreshold: js.UndefOr[Number] = _progressiveThreshold
      override val progressiveChunkMode: js.UndefOr["mod"] = _progressiveChunkMode
      override val coordinateSystem: js.UndefOr[CoordinateSystemType] = _coordinateSystem
      override val hoverLayerThreshold: js.UndefOr[Number] = _hoverLayerThreshold
      override val seriesLayoutBy: js.UndefOr[SeriesLayoutBy] = _seriesLayoutBy
      override val labelLine: js.UndefOr[LabelLineOption] = _labelLine
      override val labelLayout: js.UndefOr[LabelLayoutOption | LabelLayoutOptionCallback] = _labelLayout
      override val stateAnimation: js.UndefOr[AnimationOption] = _stateAnimation
      override val universalTransition: js.UndefOr[Boolean | UniversalTransitionOption] = _universalTransition
      override val selectedMap: js.UndefOr[js.Dictionary[Boolean] | "all"] = _selectedMap
      override val selectedMode: js.UndefOr["single" | "multiple" | "series" | Boolean] = _selectedMode
      override val lineStyle: js.UndefOr[LinesLineStyleOption[js.Function1[CallbackDataParams, ZRColor] | ZRColor]] = _lineStyle
      override val label: js.UndefOr[SeriesLineLabelOption] = _label
      override val xAxisIndex: js.UndefOr[Number] = _xAxisIndex
      override val yAxisIndex: js.UndefOr[Number] = _yAxisIndex
      override val xAxisId: js.UndefOr[String] = _xAxisId
      override val yAxisId: js.UndefOr[String] = _yAxisId
      override val geoIndex: js.UndefOr[Number] = _geoIndex
      override val geoId: js.UndefOr[String] = _geoId
      override val polarIndex: js.UndefOr[Number] = _polarIndex
      override val polarId: js.UndefOr[String] = _polarId
      override val calendarIndex: js.UndefOr[Number] = _calendarIndex
      override val calendarId: js.UndefOr[String] = _calendarId
      override val large: js.UndefOr[Boolean] = _large
      override val largeThreshold: js.UndefOr[Number] = _largeThreshold
      override val symbol: js.UndefOr[js.Array[String] | String] = _symbol
      override val symbolSize: js.UndefOr[js.Array[Number] | Number] = _symbolSize
      override val effect: js.UndefOr[LineDrawEffectOption] = _effect
      override val polyline: js.UndefOr[Boolean] = _polyline
      override val clip: js.UndefOr[Boolean] = _clip
      override val dimensions: js.UndefOr[DimensionDefinitionLoose | js.Array[DimensionDefinitionLoose]] = _dimensions
      override val markArea: js.UndefOr[MarkAreaOption] = _markArea
      override val markLine: js.UndefOr[MarkLineOption] = _markLine
      override val markPoint: js.UndefOr[MarkPointOption] = _markPoint
      override val tooltip: js.UndefOr[SeriesTooltipOption] = _tooltip
    linesSeriesOption.clean
